spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board_db
    username: root
    password: 1234 # MariaDB 비밀번호에 맞게 수정하세요
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # 개발용 (운영에서는 validate)
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  security:
    user:
      name: admin # 기본 설정 비활성화용
      password: admin

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: mySecretKey1234567890123456789012345678901234567890
  expiration: 86400000 # 24시간 (밀리초)

server:
  port: 8080
